name: flutter_mobile_vision
description: Flutter implementation for Google Mobile Vision. Scan Barcodes, Recognize Text and Detect Faces.
version: 0.1.3
homepage: https://github.com/seimus96/mobile_vision

dependencies:
  flutter:
    sdk: flutter
  rflutter_alert: ^1.0.2
  http: ^0.12.0+2


flutter:
  plugin:
    androidPackage: io.github.edufolly.fluttermobilevision
    pluginClass: FlutterMobileVisionPlugin

environment:
  sdk: ">=2.0.0-a <3.0.0"
  
